install.packages("lingtypology")
library(lingtypology)

# The Original Sample
df_original <- data.frame(language = c("Basque",
                                       "Czech",
                                       "Russian",
                                       "Hindi",
                                       "Estonian",
                                       "Spanish",
                                       "French",
                                       "Latin",
                                       "Polish",
                                       "German",
                                       "Finnish",
                                       "Urdu",
                                       "Latvian",
                                       "Norwegian",
                                       "Western Farsi",
                                       "Japanese",
                                       "Croatian Standard",
                                       "Slovenian",
                                       "English",
                                       "Standard Hebrew",
                                       "Mandarin Chinese",
                                       "Standard Indonesian",
                                       "Serbian Standard",
                                       "Slovak"),
                          feature = c("Active-inactive",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Tripartite",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Neutral",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Tripartite",
                                      "Nominative-accusative",
                                      "Neutral",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Neutral",
                                      "Nominative-accusative",
                                      "Neutral",
                                      "Neutral",
                                      "Nominative-accusative",
                                      "Nominative-accusative"))

map.feature(df_original$language,
            df_original$feature,
            label = df_original$language,
            color= "magma",
            tile = "Esri.WorldGrayCanvas")

# The Balanced Sample
df_balanced <- data.frame(language = c("Afrikaans",
                                       "Eastern Armenian",
                                       "Basque",
                                       "Mandarin Chinese",
                                       "Georgian",
                                       "Greek",
                                       "Hungarian",
                                       "Standard Indonesian",
                                       "Irish",
                                       "Japanese",
                                       "Javanese",
                                       "Korean",
                                       "Latin",
                                       "Latvian",
                                       "Western Farsi",
                                       "Tamil",
                                       "Thai",
                                       "Vietnamese",
                                       "Hindi",
                                       "Finnish",
                                       "Turkish",
                                       "Arabic",
                                       "Russian",
                                       "Portuguese"),
                          feature = c("Neutral",
                                      "Nominative-accusative",
                                      "Active-inactive",
                                      "Neutral",
                                      "Active-inactive",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Neutral",
                                      "Neutral",
                                      "Nominative-accusative",
                                      "Austronesian",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Neutral",
                                      "Neutral",
                                      "Tripartite",
                                      "Nominative-accusative",
                                      "Nominative-accusative",
                                      "Neutral",
                                      "Nominative-accusative",
                                      "Neutral"))

map.feature(df_balanced$language,
            df_balanced$feature,
            label = df_balanced$language, 
            color= "magma",
            tile = "Esri.WorldGrayCanvas")